#!/usr/bin/env bash

LAUNCH_ARGS=""                         # Use this for args like prime-run or gamemoderun!
export PRESSURE_VESSEL_FILESYSTEMS_RW= # Add your external disks paths here if you use symlinks

export WINEDEBUG=${WINEDEBUG:-}
export WINEESYNC=1                                   # PROTON_NO_ESYNC=1 is also needed to disable
export WINEFSYNC=1                                   # PROTON_NO_FSYNC=1 is also needed to disable
export WINE_BLOCK_GET_VERSION=0                      # Set this to 1 to enable Windows fonts/boss key, but it might cause crashes in future updates! Revert back if so.
export WINE_DISABLE_VK_CHILD_WINDOW_RENDERING_HACK=1 # Fixes compat. mode crashing after Proton-osu-9-15
export PROTONPATH="$HOME/.local/share/osuconfig/proton-osu"
export WINESERVER_PATH="$PROTONPATH/files/bin/wineserver"
export WINE_PATH="$PROTONPATH/files/bin/wine"
export WINETRICKS_PATH="$PROTONPATH/protontricks/winetricks"
export GAMEID="umu-727"
UMU_RUN="$PROTONPATH/umu-run"

export WINEARCH=win64
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix"
export OSUPATH="$HOME/osu"

export vblank_mode=0      # Disables vsync for mesa
export mesa_glthread=true # enable threaded OpenGL optimizations for AMD/Intel GPUs

export __GL_SYNC_TO_VBLANK=0         # Disables vsync for NVIDIA >=510
export __GL_THREADED_OPTIMIZATIONS=1 # Enable threaded OpenGL optimizations for NVIDIA
export __GL_MaxFramesAllowed=0       # minimize pre-render frames for NVIDIA

export WINEDLLOVERRIDES=winemenubuilder.exe=d# # Blocks wine from creating .desktop files

SessionType() {
  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    export WINE_ENABLE_ABS_TABLET_HACK="${WINE_ENABLE_ABS_TABLET_HACK:-2}"
    sleep 10
    if grep -q "OpenTabletDriver.Desktop.Output.AbsoluteMode" "$HOME/.config/OpenTabletDriver/settings.json"; then
      sed -i 's/OpenTabletDriver.Desktop.Output.AbsoluteMode/OpenTabletDriver.Desktop.Output.LinuxArtistMode/g' "$HOME/.config/OpenTabletDriver/settings.json"
      systemctl --user restart opentabletdriver
      sleep 2
      sed -i 's/OpenTabletDriver.Desktop.Output.LinuxArtistMode/OpenTabletDriver.Desktop.Output.AbsoluteMode/g' "$HOME/.config/OpenTabletDriver/settings.json"
      systemctl --user restart opentabletdriver
    fi
  else
    export WINE_ENABLE_ABS_TABLET_HACK="${WINE_ENABLE_ABS_TABLET_HACK:-0}"
  fi
}

export TOSU_OSU_PATH="${TOSU_OSU_PATH:-$HOME/osu!}"

export STAGING_AUDIO_PERIOD=6667
export STAGING_AUDIO_DURATION=13333

LaunchOsu() {
  "env PROTONFIXES_DISABLE=1" $LAUNCH_ARGS "$UMU_RUN" "$OSUPATH/osu!.exe" -devserver akatsuki.gg # osu! launcher
}

LaunchOsu &
SessionType
