#!/usr/bin/env bash
export WINEESYNC=1 # PROTON_NO_ESYNC=1 is also needed to disable
export WINEFSYNC=1 # PROTON_NO_FSYNC=1 is also needed to disable
export UMU_RUNTIME_UPDATE=0 # Setting Steam Runtime updates off by default
export PROTONPATH="$HOME/.local/share/osuconfig/proton-osu"
export WINESERVER_PATH="$PROTONPATH/files/bin/wineserver"
export WINE_PATH="$PROTONPATH/files/bin/wine"
export WINETRICKS_PATH="$PROTONPATH/protontricks/winetricks"
export GAMEID="osu-wine-umu"
UMU_RUN="$PROTONPATH/umu-run"

export WINE_BLOCK_GET_VERSION=1 # Hides wine ver. thanks to oglfreak's patch
export WINEARCH=win64
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix"
export OSUPATH="$HOME/osu"
export vblank_mode=0            # Disables vsync for mesa
export __GL_SYNC_TO_VBLANK=0    # Disables vsync for NVIDIA >=510
export WINEDLLOVERRIDES=winemenubuilder.exe=d# # Blocks wine from creating .desktop files
export WINE_ENABLE_GLCHILD_HACK=1 # Set this to 0 to fix black top-panel in editor!
export WINE_ENABLE_ABS_TABLET_HACK=0 # Set this to 1 to play with absolute mode in OTD on Wayland (might cause issues with cursor, but feel free to try!)

export STAGING_AUDIO_DURATION=13333 #1.333ms at 48KHz
export STAGING_AUDIO_PERIOD=13333 #1.333ms at 48KHz

$UMU_RUN $OSUPATH/osu!.exe -devserver gatari.pw # osu! launcher
