#!/usr/bin/env bash

LAUNCH_ARGS="env PROTONFIXES_DISABLE=1" # Use this for args like prime-run or gamemoderun!
export PRESSURE_VESSEL_FILESYSTEMS_RW= # Add your external disks paths here if you use symlinks

export WINEDEBUG=${WINEDEBUG:-}
export WINEESYNC=1 # PROTON_NO_ESYNC=1 is also needed to disable
export WINEFSYNC=1 # PROTON_NO_FSYNC=1 is also needed to disable
export WINE_BLOCK_GET_VERSION=0 # Set this to 1 to enable Windows fonts/boss key, but it might cause crashes in future updates! Revert back if so.
export PROTONPATH="$HOME/.local/share/osuconfig/proton-osu"
export WINESERVER_PATH="$PROTONPATH/files/bin/wineserver"
export WINE_PATH="$PROTONPATH/files/bin/wine"
export WINETRICKS_PATH="$PROTONPATH/protontricks/winetricks"
export GAMEID="umu-727"
UMU_RUN="$PROTONPATH/umu-run"

export WINEARCH=win64
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix"
export OSUPATH="$HOME/osu"
export vblank_mode=0            # Disables vsync for mesa
export __GL_SYNC_TO_VBLANK=0    # Disables vsync for NVIDIA >=510
export WINEDLLOVERRIDES=winemenubuilder.exe=d# # Blocks wine from creating .desktop files
export WINE_ENABLE_ABS_TABLET_HACK=0 # Set this to 1 to play with absolute mode in OTD on Wayland (might cause issues with cursor, but feel free to try!)

export STAGING_AUDIO_DURATION=13333 #1.333ms at 48KHz
export STAGING_AUDIO_PERIOD=13333 #1.333ms at 48KHz

$LAUNCH_ARGS "$UMU_RUN" "$OSUPATH/osu!.exe" # osu! launcher
