#!/usr/bin/env bash

LAUNCH_ARGS="" # Put arguments like prime-run, gamemoderun, or mangohud in between the quotes here!

# Set this to your external disk paths if you use symlinks!
export PRESSURE_VESSEL_FILESYSTEMS_RW="${PRESSURE_VESSEL_FILESYSTEMS_RW:-}"

# Set this to 1 or 2 to play with absolute mode in OTD on Wayland (if this doesn't work, check the "Tablet issues" page in the osu-winello wiki)
export WINE_ENABLE_ABS_TABLET_HACK="${WINE_ENABLE_ABS_TABLET_HACK:-0}"
# Set this to 1 to enable Windows fonts/boss key, but it might cause crashes in future updates! Revert back if so.
export WINE_BLOCK_GET_VERSION="${WINE_BLOCK_GET_VERSION:-0}"
# Set this to 1 to force fixes for alt-tab (only if needed!)
export WINE_ENABLE_OSU_FOCUS_FIX="${WINE_ENABLE_OSU_FOCUS_FIX:-0}"

# Enables NTsync (when possible, requires Linux >=6.14 or the DKMS module installed)
export WINENTSYNC="${WINENTSYNC:-0}"
# Enables Fsync (when possible)
export WINEFSYNC="${WINEFSYNC:-1}"
# Enables Esync (when possible)
export WINEESYNC="${WINEESYNC:-1}"

# Uncomment the line below to try the native winewayland.drv driver (unsupported, but feel free to experiment if you're on Wayland)
# export DISPLAY=

# Set custom logging channels for Wine
export WINEDEBUG="${WINEDEBUG:-}"

# Disables vsync for mesa
export vblank_mode="${vblank_mode:-0}"
# Put true after :- to enable threaded OpenGL optimizations for AMD/Intel
# (unsupported, use at your own risk! May INCREASE FPS, but may also INCREASE input latency due to multithreading overhead)
export mesa_glthread="${mesa_glthread:-}"

# Disables vsync for NVIDIA >=510
export __GL_SYNC_TO_VBLANK="${__GL_SYNC_TO_VBLANK:-0}"
# Put 1 after :- to enable threaded OpenGL optimizations for NVIDIA
# (unsupported, use at your own risk! May INCREASE FPS, but may also INCREASE input latency due to multithreading overhead)
export __GL_THREADED_OPTIMIZATIONS="${__GL_THREADED_OPTIMIZATIONS:-}"
# Put 1 after :- to minimize the pre-rendered frames for NVIDIA (driver default is 2, 0 does nothing)
# (unsupported, use at your own risk! Will LOWER FPS for a slightly LOWER input latency)
export __GL_MaxFramesAllowed="${__GL_MaxFramesAllowed:-}"

export STAGING_AUDIO_PERIOD=6667
export STAGING_AUDIO_DURATION=13333

###################################################################################################
# osu-winello internal variables, you probably don't have to touch these!
###################################################################################################

export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export BINDIR="${BINDIR:-$HOME/.local/bin}"

export YAWL_PATH="$XDG_DATA_HOME/osuconfig/yawl-winello"
export WINESERVER_PATH="${YAWL_PATH}server"
export WINE_PATH="$XDG_DATA_HOME/osuconfig/wine-osu"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/osu-wineprefix"

export WINEDLLOVERRIDES="winemenubuilder.exe=;" # Blocks wine from creating .desktop files

echo "Launching osu!: $HOME/osu/osu!.exe"
$LAUNCH_ARGS $YAWL_PATH "$HOME/osu/osu!.exe"
